server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: WARN
        type:
          descriptor:
            sql:
              BasicBinder: WARN
      springframework:
        orm:
          jpa: WARN
          jpa.JpaTransactionManager: WARN
        transaction: WARN
        transaction.interceptor: WARN
      lazymoneytracker:
        lazymoneytracker: DEBUG


spring:
  config:
    activate:
      on-profile: ci,test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/balance
    username: root
    password: root
